id: A5A125959
base_file: f3174.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:27:26.942774
  last_modified_at: 2022-06-11 13:27:26.942780
