id: A5A125959
base_file: fB55A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:27:26.947237
  last_modified_at: 2022-06-11 13:27:26.947244
